### PR TITLE
Acorn 4.x

### PR DESCRIPTION
**Pull request by jbboehr**
I'm trying to get all of Buble's dependencies working on acorn 4.x for packaging reasons. Buble's tests pass with acorn 4.x in #2, but not with commit 0da4568, so I've reverted it and proposed this PR.

### CODE REVIEW

**Comment by jbboehr** [comment]
ping @dariocravero

**Comment by victor-homyakov** [comment]
ping @dariocravero any progress?

**Comment by Rich-Harris** [comment]
FYI I've merged this into my fork (https://github.com/Rich-Harris/acorn-object-spread) so that I can update Bublé — you can `npm install Rich-Harris/acorn-object-spread` until Dario is able to merge this

**Comment by adrianheine** [comment]
I updated the plugin to acorn 5, see my fork: https://github.com/adrianheine/acorn5-object-spread
While this pull request is compatible with acorn 5, it also degrades acorn 5's support for `async` as property name.

**Comment by dariocravero** [comment]
Hey everyone, I'm sorry for not being able to follow up on this.

@adrianheine, I see your fork is already merged in buble which makes sense.

I can make you a collaborator on npm or transfer the ownership of the package to you if you're happy with that.

As for the repo, I don't mind where it is, I can add you all to this repo if you want to continue using it or it can move to Adrian's. I can merge your changes here.

**Comment by adrianheine** [comment]
Hi @dariocravero, if you want to be an active maintainer I'm happy with moving development back into this repo and your npm package. I'd like to be a collaborator at both places then :)

**Comment by dariocravero** [comment]
Hi @adrianheine, I don't think I'll be able to actively maintain it, as in, write code for it, these days. If you feel more comfortable working on your own repo, that's ok with me, I can close this one and put a note on the README saying it moved over to your GitHub. I'm also happy to give you the NPM package name, if you want to use it.

**Comment by Scrum** [comment]
@adrianheine @dariocravero ping ?

**Comment by adrianheine** [comment]
Sorry for the silence. How about we move this repo to the new acornjs organization?

**Comment by dariocravero** [comment]
@adrianheine how do we go about it? :)

**Comment by adrianheine** [comment]
I think you can just transfer ownership in the repository settings.

**Comment by dariocravero** [comment]
@adrianheine, just tried but github tells me `You don’t have the permission to create repositories on acornjs` :(

**Comment by adrianheine** [comment]
I finally figured out an obvious way to do this: You could add me to this repo since I can create repositories on acornjs.

**Comment by dariocravero** [comment]
@adrianheine done! Thanks!

**Comment by adrianheine** [comment]
Since acorn 5.4 has support of rest and spread properties builtin, I think we can just deprecate this repository and package. I'm gonna do the same with acorn5-object-spread.

**Pull request closed without merging**
